### ISSUE TITLE
Test `layout.width/height` on all widgets

### ISSUE THREAD

**Issue by ellisonbg** [jupyter-widgets/ipywidgets#1133]
In the Widget Alignment example, there was some calls to the older height/width attributes on a dropdown and slider. Those didn't work, so I updated them to use `layout.width/height`. The width worked fine but the height increased the size of the outer div container, but the actual viewable widget didn't change at all. We need to audit the behavior and styling of all the widgets to make sure that `layout.width/height` works as expected. In particular, I often want to make widgets smaller, basically changing the base width/height of all widgets. I don't think that works well right now.

Because all such fixes would be considered bug fixes, this can wait until 6.1. I think the best way of doing this is to create a companion notebook to Widget List that makes each widget larger and smaller. Then we can regularly run that notebook as a test.

**Comment by jasongrout** [comment]
Here is a full-size screenshot of the current behavior:

![localhost-8889-notebooks-docs-source-examples-widget 20list ipynb](https://user-images.githubusercontent.com/192614/27440757-b35b8c0e-5739-11e7-83f6-2319d424ba02.png)

**Comment by jasongrout** [comment]
Here is a screenshot of the current behavior:

![localhost-8889-notebooks-docs-source-examples-widget 20list ipynb 1](https://user-images.githubusercontent.com/192614/27440910-10201400-573a-11e7-993e-1171667d48bd.png)

**Comment by jasongrout** [comment]
Here's a screenshot of the current behavior:

![screen shot 2017-06-22 at 11 25 11-fullpage](https://user-images.githubusercontent.com/192614/27442217-96b00018-573d-11e7-82b8-510654eca7f1.png)

**Comment by JazzTap** [comment]
https://gist.github.com/JazzTap/562409b4ec30bb1e2bb58338737ee251

Minimal new css for widget flex layout and its children. Source only exists in npm package, can't PR this repo.

* Don't [align-self: stretch] _Sliders, which clobbers the _box's preference.
* Don't clobber long labels: use min-width, not width.
* Distribute content in boxes by default.
* Play buttons can grow vertically, consistent with ToggleButtons (see proposal below).

### NOT FIXED

FEATURE / BUGFIX: min-width of label not Python-configurable, due to being a child element of the slider/whatever.

FEATURE / ELEGANCE: If user actually wanted a float, they'd ask for an HBox. So widgets **should use** as much of their personal width/height as possible.

.widget-hprogress { height: 100% } and .widget-vprogress { width: 100% } cause the progress bar to floodfill like a toggle button.

Sliders use custom shapes, to be investigated. Valid can use a Unicode checkmark. But a scaling Unicode Checkbox still has to be clicky (onClick, appropriate cursor).


weird mutability issue: radio buttons run away from clicks, as margin-bottom of widget-radio-box counts up like +6px mod 32px every time the widget updates. expected value is var(--jp-widgets-radio-item-height-adjustment) == 8px.

inconsistent DOM manipulation: Checkbox has an empty label / left margin regardless of description (which displays floating right). Valid widgets lose their label / left margin if description is blank.

Some cosmetic niggles that don't impact functionality:

* Selection slider value can change the slider's length, e.g. while being edited.
* Right alignment of labels on tall elements (selectmultiple) doesn't look as good as centering.
* $$floating equations$$ in HTMLMath are not centered.
* Changing the aspect ratio of an Image is not prevented (which would be opinionated).

**Comment by stargaser** [comment]
@JazzTap - I believe the source for `widgets-base.css` is in `packages/controls/css` and is propagated to the npm package during the build process. Would you be willing to incorporate your css changes there and make a PR? Or I can do it if you prefer, just let me know.

@jasongrout - how did you make your full-notebook png of the entire widget list notebook? It would be useful for comparing the proposed css changes from @JazzTap.

**Comment by jasongrout** [comment]
I used something like https://stackoverflow.com/a/14830242, but it looks
like you can also use  https://screenshots.firefox.com

**Comment by jasongrout** [comment]
@JazzTap - thanks for a detailed audit of behavior, and for your work in the css! I'll just note two things:

> Checkbox has an empty label / left margin regardless of description (which displays floating right).

The checkbox description should be to the right of the checkbox - that's consistent with every other system we looked into. In order to make it line up, though, we have the `indent` parameter which adds extra space to the left of the checkbox.


> Don't clobber long labels: use min-width, not width.

I'm not exactly sure what you are referring to, but we very explicitly use width for descriptions of controls so that things line up nicely when controls are stacked. The width can be adjusted easily with the `.layout.description_width` parameter, which can also be set to `'initial'` to have descriptions sized to the content.

**Comment by jasongrout** [comment]
> I believe the source for widgets-base.css is in packages/controls/css and is propagated to the npm package during the build process.

That's exactly right. Change that file and run `npm run build` at the top level to rebuild everything to incorporate the changes.

**Comment by jasongrout** [comment]
I've made a PR for the changes by @JazzTap at https://github.com/jupyter-widgets/ipywidgets/pull/1528

**Comment by JazzTap** [comment]
> The width worked fine but the height increased the size of the outer div container, but the actual viewable widget didn't change at all. 

Sliders are now centered but still float. Font size fixed pending, say, dashboarding ([jupyterlab#1640](https://github.com/jupyterlab/jupyterlab/issues/1640)).

However, the handle is the pertinent interactive area (excepting #1351), along with the 16x16 checkboxes and radiobuttons. Looking into embiggening.

> We need to audit the behavior and styling of all the widgets to make sure that layout.width/height works as expected.

Descriptions (i.e. inline hboxes) that align in stacks are a major special case. Maybe layout.width should be **added to** layout.description_width?

UI usability is unstable to description addition/removal otherwise. Also would clarify that there is no support for ~~layout.description_height~~.

> In particular, I often want to make widgets smaller, basically changing the base width/height of all widgets. I don't think that works well right now.

Fixing up this use case now (200x20, 20x120, 80x80). Button text needs to wrap at this point, not ellipsize. Sliders and radio buttons a tad broken. Color and date pickers look good to start with!

[modified testbed](https://gist.github.com/JazzTap/562409b4ec30bb1e2bb58338737ee251/#file-layout-test-ipynb) available as raw notebook while I try to get the fullpage screenshot working on my chrome+linux.

**Comment by jasongrout** [comment]
I had issues trying to do a full-page screenshot in chrome - it had a maximum height that was way too small. I used firefox and it worked great.

**Comment by jasongrout** [comment]
As a general rule, I'd personally like to do only minimal tweaks to the UI at this point (just before a release), and not try to make major changes such as shrinking or expanding lots of elements, as changing the UI involves a *lot* of testing different configurations to see how it looks. It may be better to wait until we release 7 to work on a major refresh of the UI.

**Comment by jasongrout** [comment]
That said, if you're willing to do the work for a (small?) UI refresh/tweaks, let's discuss it.

Thanks again for working on this!

**Comment by jasongrout** [comment]
I was testing out the latest master in JupyterLab and noticed a few problems:

<img width="1206" alt="screen shot 2017-07-24 at 10 57 36 am" src="https://user-images.githubusercontent.com/192614/28529642-19cb51c0-705f-11e7-9864-68d802948749.png">

Reverting https://github.com/jupyter-widgets/ipywidgets/pull/1528/files#diff-64f2c6f929b3f8be9624c2cafa01b55eL87 fixed the issue with the slider not being aligned with its description and readout. Reverting https://github.com/jupyter-widgets/ipywidgets/pull/1528/files#diff-64f2c6f929b3f8be9624c2cafa01b55eR94 fixed the issue with the controls being too far apart (since the controls are designed to be tiled, we tried to add enough margins they would like nice without having to have extra space inserted).

Fixing CSS issues is very tricky! @JazzTap - what do you think - revert the above changes, or do you have other ideas about how to make these changes work well?

**Comment by jasongrout** [comment]
It also seems that if I set `align-items: center` on just the slider inline-hbox that the slider uses, without reverting https://github.com/jupyter-widgets/ipywidgets/pull/1528/files#diff-64f2c6f929b3f8be9624c2cafa01b55eL87, the baseline of the text elements line up appropriately for both the slider and it matches the baseline of the textbox:

<img width="1206" alt="screen shot 2017-07-24 at 11 14 35 am" src="https://user-images.githubusercontent.com/192614/28530285-525ba07e-7061-11e7-992d-bfb5577c8320.png">

**Comment by JazzTap** [comment]
The standing convention of fixed-width tiling elements seems stable for 7.0, then. Thanks for cleaning up my attempt - I apologize for not testing combined widgets in an hbox. (I will install JupyterLab as well. There is a little inherited CSS that I worry may differ. But certainly there will be a departure from the three fixed Notebook widths.)

There is simply no well-defined way of shrinking fixed-width elements, which makes ~~customization~~ workflow optimization annoying. Something has to be done about the fixed padding that agrees with the surrounding layout convention.

By introducing [grid css](https://medium.com/@fionnachan/dynamic-number-of-rows-and-columns-with-css-grid-layout-and-css-variables-cb8e8381b6f2) (which generalizes multi-column css, e.g. [masonry](https://codeburst.io/how-to-pure-css-masonry-layouts-a8ede07ba31a)) we could distribute flexbox clusters (hbox+vbox ['grids'](https://philipwalton.github.io/solved-by-flexbox/demos/grids/) - incl' described elements, - or tabs / accordions) at large page-width, and reduce to left-alignment for narrow pages or single elements. The grid wrapper just has to be given row and column counts (incl' fixed sizes), and _it will tell_ the elements how wide and tall they should be.

That is, it will do no good to teach the elements to scale robustly without putting them in a (newly explicit) container which gives them sensible default scales. It should feel the same as vstacking elements unless hboxed, but expand horizontally first and scale to different page-widths.

The implicit layout has hit its scaling limit, so I argue a grid layout will be needed for dashboarding. But I will iterate before delving into that much more extensive discussion.

**Comment by jasongrout** [comment]
Thanks for your thoughts and iterations on this!

> The implicit layout has hit its scaling limit, so I argue a grid layout will be needed for dashboarding.

I agree that we should be looking at smarter containers (such as a grid-based container) to build more complex UIs. Thanks again for looking beyond where we are and at where it makes sense to go.

**Comment by jasongrout** [comment]
I think between JazzTap's work and #1565, we can close this issue, and iterate again on the UI later (and particularly iterate on easy ways to lay out widgets, as @JazzTap points out above).

The one inconsistency I'll note here is that when the heights are expanded, some widgets center themselves and their labels (like dropdowns, progress bar, sliders) and others stay at the top (like select boxes, text boxes, checkbox and radios). This is partly because we are using baseline alignment on textboxes, and partly because lists of text look better with the label at the top.
