### ISSUE TITLE
jupyter-js-widgets release missing on npm

### ISSUE THREAD

**Issue by ssunkara1** [jupyter-widgets/ipywidgets#1230]
`ipywidgets` master depends on `jupyter-js-widgets 3.0.0` which is not available on `npm`. When I try to install `ipywidgets` I get the error `npm ERR! notarget No compatible version found: jupyter-js-widgets@~3.0.0`.

**Comment by jasongrout** [comment]
Right. For now, you'll need to do `npm run update` in widgetsnbextension, or use `npm link`.

**Comment by ssunkara1** [comment]
I tried `npm run update` and I get the following error:

ERROR in ./src/extension.js
Module not found: Error: Cannot resolve module '@phosphor/widgets/style/index.css' in D:\code\ipywidgets\widgetsnbextension\src
 @ ./src/extension.js 99:12-56

ERROR in ./src/widgetarea.js
Module not found: Error: Cannot resolve module '@phosphor/messaging' in D:\code\ipywidgets\widgetsnbextension\src
 @ ./src/widgetarea.js 7:16-46

ERROR in ./src/widgetarea.js
Module not found: Error: Cannot resolve module '@phosphor/widgets' in D:\code\ipywidgets\widgetsnbextension\src
 @ ./src/widgetarea.js 8:15-43

**Comment by jasongrout** [comment]
Thanks. We're aware of the issues. Right now, master is a bit hard to install because we're redoing how version numbers work, and we don't want to release jupyter-js-widgets until we finish https://github.com/jupyter-widgets/ipywidgets/pull/1228.

Closing for now (verified in conversation that @ssunkara1 installed 6.0 and is happy with that for now).
