### ISSUE TITLE
Implementing widgets for other language kernels

### ISSUE THREAD

**Issue by joeltg** [jupyter-widgets/ipywidgets#1286]
I'm working on a Jupyter kernel for MIT Scheme ([here](https://github.com/joeltg/mit-scheme-kernel)) and am having trouble implementing widgets. But the documentation is kind of sparse and I'm not sure what to try next :-/

I think it successfully registers a comm target (I receive a `{"frontend_version": "2.1.4", "validated": true}` comm message in the kernel and the Jupyter Notebook logs `"Widget backend and frontend versions are compatible"` and everything), but when I try to actually create and display a widget, the Jupyter Notebook logs this JavaScript error: 
```
Error: Could not determine where the display message was from. 
Widget will not be displayed at WidgetManager.display_view
```

The example I'm trying to replicate is
```python
from ipywidgets import *
IntSlider()
```
I logged all the comm activity when executing this in a Python notebook, and am sending the exact same thing from the MIT Scheme kernel:
1. a `comm_open` for a `SliderStyleModel` with a `StyleView`
2. a `comm_open` for a `LayoutModel` with a `LayoutView`
3. a `comm_open` for a `IntSliderModel` with a `IntSliderView` with references to the comm ids of 1) and 2)
4. a `comm_msg` to display comm id 
... but nothing happens. 

If anyone has any pointers or ideas or more documentation to check out, I'd really, really appreciate it. Apologies if this isn't an appropriate issue; I'm new to Jupyter :-)

**Comment by jasongrout** [comment]
Great question. We documented the comm messages at https://github.com/jupyter-widgets/ipywidgets/blob/master/jupyter-widgets-schema/messages.md (ipywigets 6 implements version 1 of the protocol). 

Your message about not knowing where the display message is from is probably from not having a parent header tied to your message. Your comm messages should have a parent header of the message that originally executed the code - that's how the display system knows that the widget should be displayed in that particular cell. In other words, your comm messages should be in response to an execute_request message. so that the frontend knows what cell's output it should be putting things in.

Does that help?

**Comment by joeltg** [comment]
The parent header was the problem! Thank you so much!
