### ISSUE TITLE
How to define content width of Output widget

### ISSUE THREAD

**Issue by fhgd** [jupyter-widgets/ipywidgets#1311]
```python
    from IPython.display import display
    from ipywidgets import Output

    out = Output()
    with out:
        print(''.join('{:.>5}'.format(n) for n in range(5, 150, 5)))

    out.layout.border = '1.5px solid'
    #out.layout.width = '100%'    # no influence
    #out.layout.margin = '0px 0px 0px 0px'    # no influence

    display(out)
```
![grafik](https://cloud.githubusercontent.com/assets/8189473/25420714/b661b944-2a59-11e7-940d-a91cec53dbf1.png)

How can I use the whole width of the Output widget which should be approximately 115 characters in this case?

**Comment by jasongrout** [comment]
Interesting, thanks for discovering this!

Note for fixing this bug: investigating, it seems that if I disable the `display: flex` in the output area enclosing the output subarea, it works. See the screenshot, and in particular the unchecked `display: flex` in the lower right:

<img width="1050" alt="screen shot 2017-04-26 at 7 33 41 am" src="https://cloud.githubusercontent.com/assets/192614/25432575/ef0ec054-2a52-11e7-8193-001ae00dfb19.png">

**Comment by jasongrout** [comment]
Alternatively, the subarea has a calc() max width (which is weird, I don't think it should), which disabling also fixes the issue:

<img width="1027" alt="screen shot 2017-04-26 at 7 36 33 am" src="https://cloud.githubusercontent.com/assets/192614/25432634/3b2689ea-2a53-11e7-82da-273e6104d208.png">

**Comment by jasongrout** [comment]
(Both of these are issues with the notebook css, though - the fix may need to go upstream, though we can probably patch it in ipywidgets in the meantime.)

**Comment by fhgd** [comment]
Many thanks for your fast investigation!

For me (with ipywidgets 6.0.0) only the second solution (uncheck the max-width option) is working. But this leads me to a rough work-around in python
```python
out.layout.width = 'calc(100% + 14ex)'
```
which uses the total width for the content

![grafik](https://cloud.githubusercontent.com/assets/8189473/25437502/e408a29e-2a96-11e7-9335-e800a75b6b86.png)

**Comment by Ricyteach** [comment]
I think this might be related since the HTML widget also doesn't seem to take up all the space available. Compare this behavior of the HTML widget, which seems a bit unexpected: 

![image](https://cloud.githubusercontent.com/assets/4923361/25514856/dd73a696-2bad-11e7-87c1-f12a170b38bb.png)

To a custom javascript view populating the $el with the same object:

![image](https://cloud.githubusercontent.com/assets/4923361/25514912/7269f822-2bae-11e7-8de5-658da4ff9a4b.png)

**Comment by jasongrout** [comment]
Yes, very interesting.

For the original output widget, the thought just occurred to me that the nested inner output widget should have max width 100%, not 100%-14ex (otherwise there is this double subtracting of 14ex). So the solution is probably as simple as a new CSS rule for nested output widgets to make max-width 100%, or perhaps just output areas inside of jupyter output widgets have max-width of 100% - that's probably easier.
