### ISSUE TITLE
set the JavaScript version in notebook widget

### ISSUE THREAD

**Issue by cornhundred** [jupyter-widgets/ipywidgets#1405]
Is there a way to set the version of the widget front-end so that it will always get a particular version from npm? Every time I update the front-end widget library on npm it effects all previous notebooks. This is not causing a problem, but I would like to know whether it is possible to fix version that is loaded from npm.

**Comment by jasongrout** [comment]
IIRC, there is no version loaded from npm with our default extension - all that is served to the client is what you have installed. Unfortunately, since you can't have multiple versions of a python package installed, that means you get one version of the javascript.

That said, the frontend can *technically* have multiple versions of widget libraries loaded, and the python _model_module_version and _view_module_version fields are used to find the right version.

**Comment by cornhundred** [comment]
Thanks I'll look into that. Also, is it possible to embed the widget JavaScript into the notebook JSON? That seems easier than having to go to npm, but I'm probably missing something.

**Comment by jasongrout** [comment]
It is possible, but not encouraged, to explicitly have the javascript in a code cell in the notebook.

The standard way to load javascript is to install an extension. We have (or have designed in, at least) the technical capability to load multiple versions of javascript in the frontend, but we are limited by the python package system in the server. This limitation goes away in JupyterLab (i.e., we are not limited by having only one python package version).
