### ISSUE TITLE
Embed code is not working 

### ISSUE THREAD

**Issue by mwcraig** [jupyter-widgets/ipywidgets#1427]
Working on ipywidgets master and notebook master, the generated embed code for widgets does not work.

There are at least two issues:

1. The embed javascript isn't on unpkg: `<script src="https://unpkg.com/embed-jupyter-widgets@~0.2.0/dist/embed.js"></script>` generates a 404.
2. The version numbers in the generated widget details doesn't match the version in the first script tag:

```
            "model_name": "LayoutModel",
            "model_module": "@jupyter-widgets/base",
            "model_module_version": "3.0.0",
```

**Comment by maartenbreddels** [comment]
This is the code generate by [this](https://github.com/jupyter-widgets/ipywidgets/blob/master/widgetsnbextension/src/embed_widgets.js#L19), I think it should refer to a different package (for require, and the url), now 'jupyter-widgets-htmlmanager' right?

**Comment by pbugnion** [comment]
From my limited understanding:

1. The link should be `https://unpkg.com/@jupyter-widgets/htmlmanager@0.1.0/dist/index.js`.

2. I don't think the embed manager should even go to `unpkg` for widgets in `@jupyter-widgets/{base,control}` since these should be included in the library we get back from the `htmlmanager`, but this is broken in version 0.1.0 of the htmlmanager currently on unpkg.

I *think* the fixes needed for embedding to work again on master:

 - In the htmlmanager, include both `@jupyter-widgets/{base,controls}` as the special modules for which we don't go looking for modules in unpkg (at the moment, only `@jupyter-widgets/controls` is a special case).
 - Cut a new release of the htmlmanager.
 - Update the embed link.

**Comment by jasongrout** [comment]
@pbugnion - is this fixed now?

**Comment by pbugnion** [comment]
I think that we still need to:

 - release a new version of the *htmlmanager* with the changes from PR #1428. 
 - update the link for the `htmlmanager` that we show in the *Embed widgets* modal.

**Comment by jasongrout** [comment]
I just tested the embed menu in the notebook by copying the code there to a new html file, and it worked great.

**Comment by pbugnion** [comment]
Great!
