### ISSUE TITLE
Timer widget

### ISSUE THREAD

**Issue by jakirkham** [jupyter-widgets/ipywidgets#1429]
Is there some way to start a displayed running timer before a computation begins and have it stop running when the computation ends?

**Comment by jasongrout** [comment]
For each cell executed? I think this would be better done as a notebook or JupyterLab extension, or possibly even built in to the notebook itself. @williamstein implemented a timer display for every cell executed, for example.

Or are you thinking of the case where you specifically launch a computation and get a notification back when the computation finishes?

**Comment by williamstein** [comment]
In CoCalc we show how long ago the cell was executed in the upper right in light grey, and if the computation is done, how long it took.  It's incredibly useful having this extra information available when using a notebook.   I showed this to people at Amazon and Google, and I think they both (at least Amazon) pointed out that they also had time info in the upper right in their custom Jupyter-like notebooks...   So something like that is natural and useful to have.   The UI is a bit tricky though, e.g., when the screen is narrow and the input is wide; one thing that helps is making this extra information disappear if you type anything in the input box, since then there is no chance to have the extra info obstruct what you're typing...  You can try this out in CoCalc right now if you want.   I don't think I did things perfectly, and I would be OK with changing it to be consistent with what you decide to do.

**Comment by jakirkham** [comment]
So my initial thought when opening this was it would be nice to have a time widget that one could add with other widgets (e.g. a progress bar). Mainly the use case would be one where the user adds it explicitly at the end of some computation to help monitor progress and estimate when something might be done. This still would be desirable I think.

That said, I think @williamstein makes a great point. It would be really helpful to have some basic time support baked into the notebook. Perhaps it also uses this widget. Just am not sure where something like this would live. Maybe in JupyterLab?

**Comment by jasongrout** [comment]
Yes, something baked in would probably live in the JupyterLab notebook component (and +1 from me for this). Opening an issue in JupyterLab repo would be the next step.

As for a timer widget, you could experiment with that as a custom widget. The javascript side could just listen for changes in the state (i.e., running or not running) and tick based on that. There could be a separate reset signal if needed. We don't have such a widget in the base set of widget controls.

**Comment by jasongrout** [comment]
Closing as answered - please reopen if you'd like to keep discussing.

**Comment by jakirkham** [comment]
FWIW I think this [Execute Time widget]( https://github.com/ipython-contrib/jupyter_contrib_nbextensions/tree/master/src/jupyter_contrib_nbextensions/nbextensions/execute_time ) ended up working pretty nicely for my use case. Plus added some other features like date-time stamps, which turned out to be pretty handy as well.
