### ISSUE TITLE
Dropdown.options is converted from Tuple[str] -> Tuple[Tuple[str]]?

### ISSUE THREAD

**Issue by hainm** [jupyter-widgets/ipywidgets#1512]
hi

Is it intention? 
When was trying to upgrade ipywidgets version (7.0) for `nglview`, I got below error:

```bash
ipywidgets/widgets/widget_selection.py:137: in _validate_value
    return findvalue(self._options_values, value, self.equals) if value is not None else None
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

array = ('0-cartoon', '1-ball+stick', '2-ball+stick'), value = ('0-cartoon', '0-cartoon'), compare = <function <lambda> at 0x112353ed8>
```

This is a minimal code to see the auto-conversion from `Tuple[str] -> Tuple[Tuple[str]]`

![ipywidgets-7](https://user-images.githubusercontent.com/4451957/28251232-ea762f80-6a46-11e7-8c54-1ca058ad9382.png)

**Comment by hainm** [comment]
```bash
d.value = d.options[0]
```

**Comment by jasongrout** [comment]
Yes, we are now normalizing all `.options` set to the standard form, a tuple of things of the form `('label', value)`. We need to have that normalized list. Thoughts?

**Comment by hainm** [comment]
hi,

I am not sure if changing type is good. Normally, I would do something like `set_option(Tuple)`.
The conversion `d.options = Tuple` is too magic.

May be keep that in internal value? `_options`: Dict[label, value]?

**Comment by jasongrout** [comment]
I was wondering if it was too magic. The normalized value would still need to be a tuple to preserve order, not a dict.

To be backwards compatible, we'd need to allow dicts and tuples to be assigned to `.options`. Before, if `.options` was assigned a dict, then we kept it as a dict, which was then confusing if the dict is mutated (because the options wouldn't be updated). Do you think it would be too confusing/magic to convert a dict to a tuple to avoid this problem? From there, it was one small step to convert everything to the same normalized format.

**Comment by jasongrout** [comment]
Or we could break the backwards compatibility and not allow dicts anymore - the order of elements coming out of the dicts usually was not what the user wanted anyway.

**Comment by hainm** [comment]
> Or we could break the backwards compatibility and not allow dicts anymore - the order of elements coming out of the dicts usually was not what the user wanted anyway.

Go for it. ipywidges-7 already broke many other things so it won't be any further surprised. :d 

nothing can be simpler than

```
dropdown.options = ['a', 'b', 'c']
dropdown.options[0] -> 'a'
```

**Comment by jasongrout** [comment]
From a user perspective, I hope that not *that* much changed.

So:

1. Disallow dictionaries being assigned to selection `.options`. Print an error message with a suggestion to assign `dict.items()` instead.
2. Keep the `.options` to be whatever tuple it was assigned (and convert to tuple if it is a list)

**Comment by hainm** [comment]
> dict.items()

I think this returns `Iterable[Tuple[key, value]]`. Did you mean `dict.values`
If not, can you give an example about what you meant?

> Keep the .options to be whatever tuple it was assigned (and convert to tuple if it is a list)

sounds good.

**Comment by jasongrout** [comment]
> I think this returns Iterable[Tuple[key, value]]. Did you mean dict.values
> If not, can you give an example about what you meant?

We want dicts to be converted to the 'long' form for options: ('label', value) - otherwise the labels are lost.

Just to be clear, I'm imagining that the `.options` can be *either* of the form `(('label1', value1), ('label2', value2)...)` *or* of the form `('label1', 'label2', ...)`. The first form is preferred, but we'll allow the second form as a shortcut to `(('label1', 'label1'), ('label2', 'label2'), ...)`

**Comment by jasongrout** [comment]
(right now we do the automatic conversion of the shortcut `('label1', 'label2')` to the preferred form, but the change would be to preserve that shortcut form in `.options`.
