### ISSUE TITLE
Freezing Embedded HTML

### ISSUE THREAD

**Issue by chrisjsewell** [jupyter-widgets/ipywidgets#1568]
As discussed in maartenbreddels/ipyvolume#41, the embedding script should insist on specific javascript library versions.

Furthermore, I think it would be desirable to have an `offline=True` keyword in the ipywidgets/embed.py functions, such that all JavaScript package dependancies were exported to an accompanying folder. The html/js could then be used in a similar manner to standard media formats (.jpeg, .mp4,...), i.e. opened offline and (relatively) resistant to future, external changes (for instance changes to url names).

**Comment by chrisjsewell** [comment]
@maartenbreddels @jasongrout

**Comment by jasongrout** [comment]
> As discussed in maartenbreddels/ipyvolume#41, the embedding script should insist on specific javascript library versions.

Definitely +1. The tricky question is which version? If we lock the version while we are still in development, it will always be a version behind.

The logic for the embedding is split up into the (a) actual js packages loaded, and (b) the embed.js script that loads requirejs and the js packages, then looks for the widget state and widget view divs. To have an offline version, copy the dist/ directory of the html manager package, and change embed.js file to load the files locally rather than from unpkg.com.

**Comment by jasongrout** [comment]
> Definitely +1. The tricky question is which version? If we lock the version while we are still in development, it will always be a version behind.

At the very least, we could do a `^` semver range, so there is some measure of auto-updating, but if it's following semver, it will be backwards compatible.

**Comment by chrisjsewell** [comment]
Sounds good :)

On the second point, I guess if you could add some logic to embed.js, such that it tries to load locally first then falls back to unpkg.com. I think @maartenbreddels already does this for ipyvolume

**Comment by jasongrout** [comment]
Sure, that would be great. I played a bit trying to get that functionality, but didn't get it to work in the time I gave myself, but I'm happy to merge a PR for that.

**Comment by jasongrout** [comment]
Can you open another issue for the offline=True keyword?
