### ISSUE TITLE
Textarea widget not rendering in Internet Explorer 11

### ISSUE THREAD

**Issue by aowi** [jupyter-widgets/ipywidgets#1700]
Hi,

I'm not sure how to best debug this issue, so any help is much appreciated.

All widgets, except for the Textarea work fine in IE11. When trying to render a Textarea, I instead get two javascript errors (see attached screenshot).

"Could not create view"

"Could not create a view for model id <...>"

![image](https://user-images.githubusercontent.com/64353/30031608-81e12c72-9192-11e7-929c-633466dc847c.png)

**Comment by jasongrout** [comment]
Thanks for reporting this. We'll check into it.

**Comment by jasongrout** [comment]
It looks like this line: https://github.com/jupyter-widgets/ipywidgets/blob/dc757a97328d69a7b090bf3e210a1e39c9bc9e52/packages/controls/src/widget_string.ts#L195

tries to set `this.textbox.rows` to `null`, which apparently is illegal in IE 11. It does this since the default for rows is None: https://github.com/jupyter-widgets/ipywidgets/blob/master/ipywidgets/widgets/widget_string.py#L65

A possible fix is to explicitly clear the `this.textbox.rows` attribute if the value is null.

**Comment by jasongrout** [comment]
According to the HTML5 (https://www.w3.org/TR/html5/forms.html#attr-textarea-rows):

> The rows attribute specifies the number of lines to show. If the rows attribute is specified, its value must be a valid non-negative integer greater than zero. If applying the rules for parsing non-negative integers to the attribute's value results in a number greater than zero, then the element's character height is that value; otherwise, it is 2.
> Visual user agents should set the height of the control to the number of lines given by character height.

So apparently resetting means to set it to 2?

**Comment by jasongrout** [comment]
It appears that using setAttribute works fine in IE 11, even with null:

```javascript
this.textbox.setAttribute('rows', this.model.get('rows'))
```
