### ISSUE TITLE
Box Height not adjusting for HTML widget style height

### ISSUE THREAD

**Issue by rskabelund** [jupyter-widgets/ipywidgets#1726]
Not sure if this is expected, but if I have an HTML widget inside a Box widget, and if the HTML tag style affects the size of the innerHTML, the Box widget shows an overflow scroll.  I would have expected it to grow in size.  This seems to be a change in behavior from ipywidgets 5.04 to 7.01 I am seeing during my migration.

```
hb_layout = Layout(display = 'flex', align_items = 'center', flex_flow='row')

btn_plot = widgets.Button(description='Plot')

plot_msg = HTML('<span style="padding:20px;color:#FF0000;">Hello</span>')

hb_plot_btn = Box(children=[btn_plot,plot_msg], layout=hb_layout)
hb_plot_btn
```

![image](https://user-images.githubusercontent.com/18313265/30767234-cb1d97b0-9faf-11e7-906a-c00a2d89353c.png)

**Comment by jasongrout** [comment]
The problem here is that the span element you are using has a smaller height than you expect because span is an inline element by default (i.e., this is an html issue with using span, not an ipywidgets issue). Change the span to a div, or set the display style to `display: inline-block` so that the vertical height of the padding matters.

**Comment by jasongrout** [comment]
Here's an example:

```python
plot_msg = HTML('<span style="padding:20px;color:#FF0000;border:1px solid black;display:inline-block">Hello</span>')
hb_plot_btn = HBox(children=[plot_msg])
hb_plot_btn
```

**Comment by jasongrout** [comment]
This "worked" (i.e., didn't work, but appeared to work) in ipywidgets 5 because the box allowed elements to overflow the box. In ipywidgets 5, the html would be drawn outside the Box, but could mess up other layouts/overlap with other things. In ipywidgets 7, we make sure that things don't extend beyond the Box, but that exposes other problems like the use of an inline element like span.

**Comment by jasongrout** [comment]
Closing as answered, but please post here if this is not working for you, or if you have other questions.
