### ISSUE TITLE
observe() in a loop doesn't work properly

### ISSUE THREAD

**Issue by rrtucci** [jupyter-widgets/ipywidgets#1798]
The following code has 4 widgets. The first two are generated by a loop and don't work properly. When you click the first widget, it claims you clicked the second widget . The last two widgets work fine

```
import ipywidgets as widgets
from IPython.display import Image, display, clear_output

# a and b in loop
def wi_do(title, change):
    print(title, change, "\n")
for title in ['a', 'b']:
    wi = widgets.SelectMultiple(
                options= ['one', 'two'],
                value= ['one'],
                description=title
            )
    display(wi)
    wi.observe(lambda x: wi_do(title, x), names='value')
    
# A
A = widgets.SelectMultiple(
            options= ['one', 'two'],
            value= ['one'],
            description='A'
        )
display(A)
def A_do(change):
    print(A.description, change, "\n")
A.observe(A_do, names='value')

# B
B = widgets.SelectMultiple(
            options= ['one', 'two'],
            value= ['one'],
            description='B'
        )
display(B)
def B_do(change):
    print(B.description, change, "\n")
B.observe(B_do, names='value')
```

**Comment by pbugnion** [comment]
Thanks for raising this. As a temporary workaround, you can use the `change` event to access the widget that changed.

As an extra data point, `traitlets.HasTraits` behaves similarly:

```py
import traitlets

class TestHasTraits(traitlets.HasTraits):
    a = traitlets.Unicode()

tests = []
for aval in ['first', 'second']:
    has_traits = TestHasTraits(a='hello world')
    has_traits.observe(lambda change: print(aval, change), names='a')
    tests.append(has_traits)

# Now try
tests[0].a = 'bye'
# > second {'name': 'a', 'old': 'hello world', 'new': 'bye', 'owner': <__main__.TestHasTraits object at 0x7fd94433a3c8>, 'type': 'change'}
```

I couldn't find an issue related to this in traitlets.

**Comment by jasongrout** [comment]
The issue here is understanding how python lambda functions capture variables and values, and has nothing to do with ipywidgets or traitlets. For example:

```python
callbacks = []
for title in ('a','b'):
    callbacks.append(lambda x: print(title, x))

callbacks[0](' - we want a')

callbacks[1](' - we want b')
```
Basically, each lambda function refers to the global `title` in its body, but it looks up the value of `title` when it is *run*, not when it is defined. So for either function, when it is run, it substitutes in the global value of `title` after the loop, which is `'b'`. In order to capture the value of `title` at definition time, you need to either create a new scope that captures the value (not the variable reference), or a common trick is to make a default parameter for your lambda function that captures the value. For example:

```python
callbacks = []
for title in ('a','b'):
    callbacks.append(lambda x, title=title: print(title, x))

callbacks[0](' - we want a')

callbacks[1](' - we want b')
```

So a simple fix for your example above is changing the first lambda line to: `wi.observe(lambda x, title=title: wi_do(title, x), names='value')`

**Comment by rrtucci** [comment]
Thanks Jason!

**Comment by jasongrout** [comment]
Closing as answered. Please let us know if you have any other questions.
