### ISSUE TITLE
Box Widget - overflow css inconsistency

### ISSUE THREAD

**Issue by gyzmau** [jupyter-widgets/ipywidgets#1837]
Hello,

By default the overflow on a Box (css class .widget-box) is working well.
But when added into another widget it getting override by `.jupyter-widgets .p-Widget` which have the `overflow:hidden`
In the meantime I didn't find any way to set his style (via style or layout).
Here a code to reproduce it:
```
import ipywidgets as widgets
from IPython.display import display

items = [widgets.Label(str(i), layout=widgets.Layout(width='auto',min_height='20px', height='20px',display='flex')) for i in range(10)]
styleOverflowAuto = {'overflow': 'auto'}
box_layout = widgets.Layout(width='300px',display='flex',flex_flow='column', height='150px', overflow='auto')
box = widgets.Box(items, layout=box_layout, style=styleOverflowAuto)
text = widgets.Text(layout=widgets.Layout(width='300px'),placeholder='Filter', disabled=False)
component = widgets.VBox([text, box])
#overflow works well when alone
#display(box)
#Overflow doesn't work when embedded
display(component)
```

On other note, it was working before, I updated my packages including ipywidgets, I can't recall on which version I was previously. I tried to downgrade to find when the breaking change appears, but without success

Can i do anything?

**Comment by gyzmau** [comment]
In digging a bit, it looks like the issue might come from phosphorjs.

**Comment by jasongrout** [comment]
#1841 fixes one side of this issue. The other side is that giving the `overflow='auto'` in the layout *should* have worked around this problem. However, it turns out that the code at https://github.com/jupyter-widgets/ipywidgets/blob/34091c58f5f21a947503031d48f623a23fa58b86/packages/base/src/widget_layout.ts#L100 means that having both `overflow`, `overflow_x`, and `overflow_y` traits means they stomp on each other, i.e., overflow gets correctly set to 'auto', but then `overflow_x` and `overflow_y` being nothing erases the overflow value.

CC @SylvainCorlay. I think we should remove the `overflow` as a synced attribute, but for backwards compatibility we can make it a non-synced property that automatically sets `overflow_x` and `overflow_y`. Thoughts?

**Comment by jasongrout** [comment]
#1841 takes care of the erroneous override, so that closes this issue. However, we still have an issue of the overflow overriding itself - I'll open another issue for that.
