### ISSUE TITLE
Failed to display Jupyter Widget of type Figure.

### ISSUE THREAD

**Issue by Stazzy1** [jupyter-widgets/ipywidgets#1838]
I'm trying to display a map in my jupyter notebook, however I am getting this error when running the cell. I followed the setup closely although there is something just not adding up.. I'm new to python and tried to follow a couple of the other threads similar to this although still no joy. I have (hopefully) attached the image below of how my console looks. Any help would be greatly appreciated

![image](https://user-images.githubusercontent.com/33981739/33230719-c3e033d2-d1e0-11e7-8435-f74e04dafe4c.png)

![image](https://user-images.githubusercontent.com/33981739/33230730-fc05b9da-d1e0-11e7-8020-86168122518e.png)

**Comment by pbugnion** [comment]
Thanks for raising this! Since this is apriori related to [jupyter-gmaps](https://github.com/pbugnion/gmaps), rather than directly to ipywidgets, I suggest re-raising the issue there -- I'll answer you there. 

Raising the issue closer to the source will help other people who are facing the same problem.

**Comment by Stazzy1** [comment]
Hey, thanks I have moved it to there now! :)

**Comment by pbugnion** [comment]
Cross-reference issue [207](https://github.com/pbugnion/gmaps/issues/207) on jupyter-gmaps.
