### ISSUE TITLE
Document which versions of the jupyterlab manager are recommended for various jupyterlab versions

### ISSUE THREAD

**Issue by jasongrout** [jupyter-widgets/ipywidgets#1893]
Perhaps just a simple table with some explanatory text. See https://github.com/jupyterlab/jupyterlab/issues/3215 for some of the problems people have been having.
  
For exampe, JupyterLab 0.30.x is compatible with `@jupyter-widgets/jupyterlab-manager` 0.31: 
`jupyter labextension install @jupyter-widgets/jupyterlab-manager@0.31`

**Comment by JuanKRod** [comment]
I keep having errors with this - I have tried all the options. 
Can you please fix this

**Comment by vidartf** [comment]
Side note: There is work in progress in jupyterlab to prevent this issue in the future: https://github.com/jupyterlab/jupyterlab/pull/3608

**Comment by jasongrout** [comment]
@JuanKRod - the compatibility table is at https://github.com/jupyter-widgets/ipywidgets/tree/master/packages/jupyterlab-manager#version-compatibility. Does that help? What are you trying to do?

**Comment by vidartf** [comment]
@jasongrout c.f. [comment on lab issue](https://github.com/jupyterlab/jupyterlab/issues/1548#issuecomment-364074221). The issue seems to be that the table doesn't cover older versions of lab. As far as I can tell, the lab version in question is 0.27, which is why I recommended he upgrade jupyterlab.
