### ISSUE TITLE
DatePicker on Invalid Dates

### ISSUE THREAD

**Issue by mlucool** [jupyter-widgets/ipywidgets#1895]
When a DatePicker has an invalid value it is highlighted in orange as expected. The widget.value though is the last valid value which seems strange since there is a mismatch in the UI when something goes to process this.

Example:
```
import ipywidgets
def print_value(v):
    print(v)
w = ipywidgets.DatePicker()
w.observe(print_value, 'value')
w
```
Change the date from 01/31/2017 and keep pushing up on the first value as that you get 02/31/2017. `w.value` is `2017-01-31` still although this is not what the UI says.

Starting:
![image](https://user-images.githubusercontent.com/1813603/34733728-6acfc1f2-f537-11e7-8bf8-39ddd1018de4.png)
Ending:
![image](https://user-images.githubusercontent.com/1813603/34733711-5ab3589c-f537-11e7-8456-36550ab2fcd8.png)

 I would have expected it to say None as it does when it was blank when first created.

**Comment by jasongrout** [comment]
Thanks! This definitely seems like a bug, and your suggestion makes a lot of sense.

**Comment by scottdraves** [comment]
digging into this one

**Comment by scottdraves** [comment]
I tried to fix this with the obvious code (see above).  basically when the user makes an invalid date, then it syncs null instead of doing nothing.  however this has a problem that setting the value to null also means changing the widget back to its "mm/dd/yyyy" state, which is unexpected and probably not what the user was looking for.

maybe there could be another special value besides None/null that indicated the error state, but this sounds like a new feature, not fixing a bug, so I don't see any easy way to solve this as stated.

**Comment by mlucool** [comment]
What about using `NaN`? See: https://stackoverflow.com/questions/11526504/minimum-and-maximum-date

**Comment by jasongrout** [comment]
Nice find! One issue with that is `NaN` is not a proper json value.
```
> 0/0
NaN
> JSON.stringify(0/0)
"null"
```

**Comment by mlucool** [comment]
If there is a place to insert a check on the python side, it might be good for force it to string "NaN" in JSON then check for this specific value in python and parse it as an exception. What do you think?
