### ISSUE TITLE
Use widgets for output in jupyterlab kernel without a notebook

### ISSUE THREAD

**Issue by minrk** [jupyter-widgets/ipywidgets#2102]
In [thebelab](https://github.com/minrk/thebelab), I'm using the JupyterLab kernel and output-area implementations. I'd like to be able to have widgets work *if available*, by adding widgets via additional script tags. It seems that I want something similar to the `html-manager` package, but that emits the RenderMime renderer (and possibly the WidgetManager, I'm not sure).

In particular, things I do not have on the page:

- JupyterLab, DocManager, etc.
- Notebook Documents

and it looks like the widget manager and extension assume these are in use. It also appears that there isn't a script-tag-embeddable form of anything other than html-manager. Is that right?

Ideally, what I'd like people to be able to do should look like:

```html
  <script type="text/javascript" src="https://unpkg.com/@jupyter-widgets/jupyterlab-manager@0.35"></script>
  <script type="text/javascript" src="https://unpkg.com/my-custom-widget@1.0" ></script>
  <script type="text/javascript" src="https://unpkg.com/thebelab@^0.2.0" ></script>
```

and then their custom widget would be available. If they need a little code to explicitly register custom widgets with the registry, that would be okay, too, but what is a critical requirement is that folks *do not* need to run a webpack build for thebelab with every possible combination of widgets.

Can I accomplish this now, or do I need some changes here before I can get started supporting widgets?

Or would it perhaps be more feasible if I include the WidgetManager in the thebelab bundle, and I confine the no-rebuild requirement to only support for *custom* widgets via additional tags?

**Comment by SylvainCorlay** [comment]
Hey @minrk thanks for opening this. This really goes along the lines of what we are looking at with @maartenbreddels at the moment.

I think that most of the pieces are there.

- Regarding the inclusion of the script tags, I think that only the html manager should be required.
- When custom widgets are on unpkg, the classic notebook bundles will be automatically fetched by the html manager.
- Before checking on the unpkg, the local directory of the page is first checked in case you want to override, and in case of 404, it then goes to unpkg. You can see the 404 in the js console here: http://ipyleaflet.readthedocs.io/en/latest/api_reference/velocity.html

Instead of loading `embed-amd.js` which renders widget views that are on the page upon load, I think that you want `libembed-amd.js`

```html
<script type="text/javascript" src="https://unpkg.com/@jupyter-widgets/html-manager@*/dist/libembed-amd.js"></script>
```

**Comment by SylvainCorlay** [comment]
Then you should be able to render widgets by calling `renderWidgets` on the DOM element of the output area that you just created.

https://github.com/jupyter-widgets/ipywidgets/blob/05b6bcb6baeb9f1cf2e836852f0bf10a14f9b4c5/packages/html-manager/src/libembed-amd.ts#L60

**Comment by SylvainCorlay** [comment]
Looking at the code of thebelab, you could get away without calling `renderWidgets` by registering the widget renderer like we do for the output widget for the html manager.

```
renderMime.addFactory({
            safe: false,
            mimeTypes: [WIDGET_MIMETYPE],
            createRenderer: (options) => new WidgetRenderer(options, this)
        }, 0)
```

**Comment by SylvainCorlay** [comment]
Closing as we have just merged the widget support in thebelab.
