### ISSUE TITLE
Multiple versions of `d3-format` found in `jupyter-lab build`

### ISSUE THREAD

**Issue by mprogram** [jupyter-widgets/ipywidgets#2184]
Compare `ipywidgets`' `"d3-format": "^0.5.1"` with `jupyterlab`'s `"d3-format": "^1.3.0"`: 
https://github.com/jupyter-widgets/ipywidgets/blob/master/packages/controls/package.json#L78
with
https://github.com/jupyterlab/jupyterlab/blob/master/yarn.lock#L2450
and further (total: 8 instances) which, probably, causes the following warning in `jupyter-lab build`: 
```
WARNING in d3-format
  Multiple versions of d3-format found:
    0.5.1 ./~/@jupyter-widgets/controls/~/d3-format from ./~/@jupyter-widgets/controls/lib/widget_int.js                                                                       
    1.3.0 ./~/d3-format from ./~/d3-format/index.js
```
what `typescript` may consider incompatible

**Comment by SylvainCorlay** [comment]
Good catch!

I think that we should upgrade that dependency in ipywidgets! Don't hesitate to open a PR!

**Comment by jasongrout** [comment]
Thanks. We should probably upgrade the version of d3-format we use in ipywidgets. I'll mark this as a good first issue. Hopefully all we need to do is bump the version number in that package.json.

d3-format is used to format the slider readouts, so that's where to check to make sure things are still working.

**Comment by jasongrout** [comment]
Works great for me! Thanks!

**Comment by SylvainCorlay** [comment]
Closing as solved.
