### ISSUE TITLE
html-manager usage

### ISSUE THREAD

**Issue by msuperina** [jupyter-widgets/ipywidgets#2292]
I am trying to understand how to embed control widgets (for example HBox) in a standalone js client.
The backend is a remote jupyter notebook server with enabled extensions and I am using the [Jupyterlab notebook example](https://github.com/jupyterlab/jupyterlab/tree/master/examples/notebook) to render notebook contents on my standalone js client.
All the documentations and issues I read use the jupyter-manager, but there is no way here to run any jupyter command as I am on a separate purely frontend environment.
The web3 example tells a specific kernel to execute some code. However in the notebook example it is a little more complicated and it looks like there are objects to somehow register.
Is there some documentation or example somewhere which show how to use the html-manager in such scenario ?
Many thanks.

**Comment by msuperina** [comment]
After reading the source code of many widget managers I could start to understand the (documentation)[https://jupyterlab.readthedocs.io/en/stable/developer/notebook.html#the-ipywidgets-third-party-extension]. I am now able to embed control widgets in a standalone js client by importing jupyterlab-manager in the nodebook example and activating it with the DocumentRegistry passed in the configuration constructor.

```
import widgetManagerProvider from "@jupyter-widgets/jupyterlab-manager";

// ...

const docRegistry = new DocumentRegistry();
widgetManagerProvider.activate({ docRegistry });
```

Is it the only think I need to do or am I missing something ?

**Comment by jasongrout** [comment]
Great question! The jupyterlab manager is likely the thing to use if you are using the jlab notebook example, not the html manager, so you're right there.

I guess what you did works accidentally, since really the activate function takes in a JLab app. However, since the activate function only uses the docRegistry attribute, you fooled it by just passing in that single attribute.

The problem now is that the jlab notebook example doesn't use the docRegistry, so I'm surprised it works. Does it render widgets?

If not, you may need to basically call the NBWidgetExtension createNew function manually with the notebook on the page.

**Comment by msuperina** [comment]
Thanks for your answer !

I can see the DocumentManager is (injected the DocumentRegistry)[https://github.com/jupyterlab/jupyterlab/blob/26005e6f8c6373938b26c81a651e9a07455759cb/examples/notebook/src/index.ts#L105].
And not only it renders the widgets, stream messages are redirected to interactive widgets when declared.

Take this example: 
```
from ipywidgets import IntSlider, HBox, VBox, interactive_output, HTML, jslink
from IPython.display import display

a = IntSlider(description='a')
b = IntSlider(description='b')
c = IntSlider(description='c')

def f(a, b, c)
    print('{}*{}*{}={}'.format(a, b, c, a*b*c))

out1 = interactive_output(f, {'a': a, 'b': b, 'c': c })

display(HBox([VBox([a, b, c]), out1]))

out2 = HTML()
jslink((a, "value"), (out2, "value"))

display(VBox([a, out2]))
```
By playing with the web3 example and its custom widget manager based on html-manager I was able to render the widget, get the updates on the client-side linked widgets, but could not render the interactive output. 
With the jupyterlab-manager everything renders and updates, even the interactive output.

**Comment by jasongrout** [comment]
Great! I forgot that the example used the document registry.

It's still a bit fragile in that you're only passing in an object with the registry, instead of a full app like the activate function expects (so technically you're violating the function's preconditions), but it works for now! Great!

I'll close this as resolved, then? (feel free to comment if this shouldn't have been closed)
