### ISSUE TITLE
Width style for a FloatProgress widge

### ISSUE THREAD

**Issue by scottwsides** [jupyter-widgets/ipywidgets#2364]
In your description of adjusting the labels on a widget

<img width="699" alt="55843209-52d93f00-5af4-11e9-830d-d96a10a46ec5" src="https://user-images.githubusercontent.com/13578795/55884646-a768d280-5b65-11e9-93dc-37a43d29195d.png">

Could you define exactly what you mean by 'widget width'. Without using the HBox[Label.....]
construction (its not working for me) how would you edit the style = '...' above to get both the description and the widget itself wider. Also, what is the value of 'initial'? BTW, in the title I say 'FloatProgress' bar but I imagine the same solution for the case in the image above will apply.

Thanks,

**Comment by jasongrout** [comment]
The widget width (i.e., the overall width of the entire widget) can be changed with the layout attribute: `IntSlider(..., layout={'width': '600px'})`.

The values here are CSS values. 'initial' stands for the default CSS value, which for a text div is to size itself to its content. You can read more here: https://developer.mozilla.org/en-US/docs/Web/CSS/width. In particular, that page shows that the initial value of the attribute is 'auto'. Perhaps it would be clearer in the example to explicitly use 'auto' rather than 'initial'.

**Comment by scottwsides** [comment]
Got it! I can put in the following:

style = {'description_width':'initial'}
layout = {'width':'600px'}

and then have something like IntSlider(...., style=style, layout=layout)
and I can set each separately.

Thanks,
*Dr. Scott W Sides*
(303) 718-7028

**Comment by scottwsides** [comment]
I believe this was fixed by Jason's last help
