### ISSUE TITLE
Question: simple example that uses buffers

### ISSUE THREAD

**Issue by williamstein** [jupyter-widgets/ipywidgets#2378]
The ipywidgets comm messages always have `"buffers":[]` as a field.   [Searching the ipywidgets docs](https://ipywidgets.readthedocs.io/en/stable/search.html?q=buffer&check_keywords=yes&area=default) doesn't seem to mention buffers:

![image](https://user-images.githubusercontent.com/1276278/56146820-d1eacf00-5f5b-11e9-9a37-e9c6d8df6e09.png)

**Question:** What is a simple example that actually uses buffers?

Context: I'm implementing widgets with realtime sync and a different communications protocol for CoCalc, and will (presumably) have to come up with some way to implement buffers.  However, so far I don't even know how to make them get used, so I've just been ignoring them.

**Comment by jasongrout** [comment]
buffers are a jupyter message spec thing. Basically, buffers allow you to transfer binary data at the comm message layer (technically, what it does it convert the websocket frame to a binary frame instead of a text frame containing pure json). See https://jupyter-client.readthedocs.io/en/stable/messaging.html#general-message-format

We use buffers to encode binary data from widgets. We've documented how we do this in comm messages at https://github.com/jupyter-widgets/ipywidgets/blob/367d3e193bd38593e3316b9420ec729bdc56f221/packages/schema/messages.md#instantiating-a-widget-object-1 and https://github.com/jupyter-widgets/ipywidgets/blob/367d3e193bd38593e3316b9420ec729bdc56f221/packages/schema/messages.md#synchronizing-widget-state-update

The simplest example in ipywidgets that uses it is the Image widget (the source of the image is transferred in a binary buffer). See the `value` attribute of https://github.com/jupyter-widgets/ipywidgets/blob/master/packages/schema/jupyterwidgetmodels.v7-4.md#imagemodel-jupyter-widgetscontrols-140-imageview-jupyter-widgetscontrols-140

Basically, widget state can contain binary values. We have to translate that widget state to comm messages. If the widget state contains no binary values, we just encode the state as JSON and send it as a text comm message. If the widget state contains binary values, we strip the binary values out, put them in the buffers attribute of the comm message, and have another part of the message that tells us how to splice back in each buffer in the JSON structure on the other side.

For python, going from state to comm messages uses `_remove_buffers` to strip out binary data: https://github.com/jupyter-widgets/ipywidgets/blob/367d3e193bd38593e3316b9420ec729bdc56f221/ipywidgets/widgets/widget.py#L117-L130 and going from comm messages to state uses `_put_buffers` to splice back in binary data: https://github.com/jupyter-widgets/ipywidgets/blob/367d3e193bd38593e3316b9420ec729bdc56f221/ipywidgets/widgets/widget.py#L59-L69. You can search in that widget.py file for where these functions are used to see exactly how they are used.

On the js side, we have corresponding functions put_buffers: https://github.com/jupyter-widgets/ipywidgets/blob/367d3e193bd38593e3316b9420ec729bdc56f221/packages/base/src/utils.ts#L134 and remove_buffers: https://github.com/jupyter-widgets/ipywidgets/blob/367d3e193bd38593e3316b9420ec729bdc56f221/packages/base/src/utils.ts#L159. Again, you can look for where we use these functions in https://github.com/jupyter-widgets/ipywidgets/blob/367d3e193bd38593e3316b9420ec729bdc56f221/packages/base/src/widget.ts


The code that translates from an object state possibly having binary data, and the comm messages that are actually transferred is at https://github.com/jupyter-widgets/ipywidgets/blob/367d3e193bd38593e3316b9420ec729bdc56f221/ipywidgets/widgets/widget.py#L486 for the python side (and other places in that file where `remove_buffers` is called) and 

If there are any binary fields, we strip them out and

**Comment by jasongrout** [comment]
Closing as answered. Feel free to post to continue discussion if needed, though.
