### ISSUE TITLE
Incorrect argument name

### ISSUE THREAD

**Issue by kb0304** [jupyter-widgets/ipywidgets#2526]
[here](https://github.com/jupyter-widgets/ipywidgets/blob/6ec38c76fb93be0e840e8dfc96495f6e77f533fe/packages/jupyterlab-manager/src/manager.ts#L269) the argument name should be `target_name` instead of `target` here.
Right now, it intercepts all the messages irrespective of their target names.

Link to doc: [link](https://jupyter-client.readthedocs.io/en/stable/messaging.html#comm-info)

**Comment by jasongrout** [comment]
It also an issue at https://github.com/jupyter-widgets/ipywidgets/blob/6ec38c76fb93be0e840e8dfc96495f6e77f533fe/examples/web3/src/manager.ts#L53

Thanks for catching this. Do you want to submit a PR correcting these two references?

I looked at the classic notebook manager, and it uses the classic notebook code to send this message, which does use the correct `target_name` attribute.

**Comment by jasongrout** [comment]
This has been fixed in the latest patch release of JupyterLab (1.0.5), so it can be more easily fixed in ipywidgets now.

**Comment by jmk9000** [comment]
Looks like this is currently fixed in both areas. 

The web3 example:
https://github.com/jupyter-widgets/ipywidgets/blob/045cb0eeb21643373ddbd49a2a12acaad8cbb900/examples/web3/src/manager.ts#L40

And the jupyter_widgets manager:
https://github.com/jupyter-widgets/ipywidgets/blob/045cb0eeb21643373ddbd49a2a12acaad8cbb900/python/jupyterlab_widgets/src/manager.ts#L208-L210

Is this eligible to be closed?

**Comment by vidartf** [comment]
Closing as resolved!
