### ISSUE TITLE
Fetch function return value(s) in same cell

### ISSUE THREAD

**Issue by tischi** [jupyter-widgets/ipywidgets#2658]
Hello,

I am already sorry, because I feel this must have been asked many times, but I could not find a good answer. I "simply" would like to fetch the return value(s) of a function in the same cell where the interaction happens. I paste below some code to show my issue:

### Cell 01
```
def f(x):
    return x
w = interactive(f, x=10)
display(w)
out = w.result # the issue: this line is never executed if it is in same cell
```

### Cell 01
```
def f(x):
    return x
w = interactive(f, x=10)
display(w)
```

### Cell 02
```
out = w.result # this works, but is not so nice for my use-case (see discussion below)
```

## Context

I would like to sometimes call the function `f` in interactive mode and sometimes not, simply by setting a flag `do_interact = False` somewhere. In both cases I would like to fetch the output values of the function **with the same variable name(s)** (`out` in this case) such that they can be used in the next cell independent of whether they have been computed in interactive mode or in normal mode.

I found that one way to achieve this is to pass an empty list for the outputs to the function input (sort of a hack for passing outputs by-reference). In this case the output values can be populated in interactive mode and non-interactive mode in an identical manner. However, I would like to avoid this "passing outputs by-reference" as it is not very pythonic... and rather have proper return values.

I think, maybe, I would need something like a `[ Done ]` button which would terminate the `display(w)` line of code and execute the next line of code in the same cell.

I am grateful for any advice!

**Comment by jasongrout** [comment]
The code in a cell is executed all at once, so in your first example, that last line is run before the user has a chance to interact with the controls. Your second example works because it gives the user a chance to change the controls, those changes to get passed back to the kernel, and *then* asks for the result.

> I think, maybe, I would need something like a `[ Done ]` button which would terminate the `display(w)` line of code and execute the next line of code in the same cell.

There may be a way to do this with the top-level await and examples from https://ipywidgets.readthedocs.io/en/latest/examples/Widget%20Asynchronous.html. @kafonek has also explored patterns to pause execution to wait for user input in his package https://github.com/kafonek/ipython_blocking

**Comment by jasongrout** [comment]
Closing as answered. Thanks.
