### ISSUE TITLE
Notebook validation failed

### ISSUE THREAD

**Issue by jayaBalaR** [jupyter-widgets/ipywidgets#2788]
Hi
I installed latest ML lib catboost alongwith ipywidgets and nbextensions. The nbformat version is 5.0.4.
I have vizualizer widgets in my page, also the simple javascript progress bar with tqdm also does not load.
I am running the notebook on GCP.
Could you please look into and let me know the solution

Thanks

![image](https://user-images.githubusercontent.com/21074002/74919184-3e422480-53f0-11ea-9772-6cfe985dba1c.png)

**Comment by jayaBalaR** [comment]
![image](https://user-images.githubusercontent.com/21074002/74923865-857fe380-53f7-11ea-824e-69d220c4044b.png)
This is the error in ssh console in gcp

**Comment by jasongrout** [comment]
The notebook file format has versions. Your notebook file is likely claiming to be something like format 4.0 or 4.1, which does not support widgets (supported by notebook format version 4.2 or above - also note that we are talking about the notebook file itself here, nothing to do with the nbformat package).

You are seeing a problem because the nbformat python package version 5 is more careful about checking the notebook file format than nbformat package version 4.

There are a couple of ways to move forward.

1. First, you could edit the file in a text editor to bump the file format version to minor version 2 or greater (i.e., notebook file format 4.2 or greater), like we did in https://github.com/jupyter-widgets/ipywidgets/commit/11df5a15e4b320d83e28b23b6c16ced10e7640ec. This is the best fix, as it actually fixes the problem.
2. You could downgrade nbformat package to a version before version 5.0, which will then ignore that the file is not compatible.

**Comment by jasongrout** [comment]
More discussion at https://github.com/jupyter/nbformat/issues/161#issuecomment-577412867

Another option is to downgrade the nbformat python package to version 4.4 (which ignores the file noncompliance), open the file in JupyterLab, make one change, and save it (which will bump the file format to notebook file format 4.2). Basically this would be the same as hand-editing the json to bump the version number of the file.

**Comment by jayaBalaR** [comment]
Thank you . I will check these options

**Comment by jayaBalaR** [comment]
I checked downgrade of nbformat to 4.4.0 , but I still seem to get the validation error.

![image](https://user-images.githubusercontent.com/21074002/74944302-d7d2fb80-541b-11ea-9f40-3b25ede32ea5.png)
jupyter notebook version is 6.0.3
![image](https://user-images.githubusercontent.com/21074002/74945200-52e8e180-541d-11ea-9844-cf0aeef0ec30.png)

Is there anything I am missing in these steps?

**Comment by jasongrout** [comment]
> Is there anything I am missing in these steps?

Make sure to restart the notebook server so it uses nbformat 4.4 to validate the notebook.

**Comment by jayaBalaR** [comment]
> so it uses nbformat 4.4 to validate th

Yes after restarting the notebook server it works. Thank you
