### ISSUE TITLE
Imposible to set titles on tabs and accordion

### ISSUE THREAD

**Issue by Oberonhive** [jupyter-widgets/ipywidgets#2790]
In latest version can't set titles for Tabs and Accordion widgets. 
In some previous versions I've used `set_title` method, now it's unavailable.

![image](https://user-images.githubusercontent.com/10414629/74962757-95acb880-5421-11ea-81eb-1186175da4a0.png)

**Comment by jasongrout** [comment]
What version do you have?

**Comment by Oberonhive** [comment]
> What version do you have?

It's current master. 7.5.1.

**Comment by jasongrout** [comment]
Use the `set_title` method for 7.5.1. In 8.0, you'll be able to set the titles in the constructor.

**Comment by Bianca-Aguglia** [comment]
> Use the `set_title` method for 7.5.1. In 8.0, you'll be able to set the titles in the constructor.

Thank you. This worked. 😊

**Comment by williamstein** [comment]
@jasongrout I also hit this just now.  It's very confusing because doing a Google search for "ipywidgets tabs" leads me to the latest version on read-the-docs, which has documentation that doesn't work in the stable version of ipywidgets.  The correct docs for Tab for the stable version are here: https://ipywidgets.readthedocs.io/en/stable/examples/Widget%20List.html#Tabs

I wonder if there is any way to have Google prefer https://ipywidgets.readthedocs.io/en/stable/ over https://ipywidgets.readthedocs.io/en/latest/?

(I will personally just be more careful next time, of course.)

**Comment by jasongrout** [comment]
Good question. We set the default url to stable a long time ago, as you can see by going to https://ipywidgets.readthedocs.io/. I don't know how to influence Google.

Of course, even better would be releasing 8.0 so it's stable :).

**Comment by williamstein** [comment]
@jasongrout for what it is worth, in my CoCalc implementation of tabs, if they don't have titles then I'm automatically labeling them with "1", "2", "3", etc.,  rather than leaving the tabs blank like you do.  The reason is because I'm using https://ant.design/components/tabs/ as our UI library (rewriting all the bootstrap stuff to instead use antd), and the antd tabs don't work if they are empty strings (just due there not being something to click on).   Anyway, it's just a sort of funny edge case...
