### ISSUE TITLE
Retain order in select multiple ipywidgets

### ISSUE THREAD

**Issue by vignesh0710** [jupyter-widgets/ipywidgets#2812]
```
import ipywidgets as widgets

d = widgets.SelectMultiple(
options=['Apples', 'Oranges', 'Pears',"Mango"],
#rows=10,
description='Fruits',
disabled=False
)
```
OP:

```
print (list(d.value))
['Apples', 'Mango']
```
Irrespective of the order I select, the order in OP is always the same as in the order the list of options. For example, even if I select Mango first and then Apple the OP is still as given.

Is there any way to retain order when using any select Multiple widgets?

**Comment by vidartf** [comment]
This is dependent on whether the relevant browser control supports it or not (https://developer.mozilla.org/en-US/docs/Web/HTML/Element/select). If it turns out that the browser control supports it, and we are "losing" that information somewhere, we should try to fix it. Otherwise, I would say this isn't reasonable for us the handle, but a third-party widget library creating their own browser controls might implement this (if anyone knows of such an existing library, please share, or if anyone wants to write such a library, please let us know).

**Comment by jasongrout** [comment]
Note that you can infer the order by just listening to the selections as they happen and updating your list. Every new addition to the selected items should trigger a new update to `.value`.
