### ISSUE TITLE
Guidelines for using jupyter-js-widgets in non-notebook

### ISSUE THREAD

**Issue by DonJayamanne** [jupyter-widgets/ipywidgets#2986]
### Problem

Today the [Python extension for VS Code](https://github.com/microsoft/vscode-python) supports IPyWidgets with a custom Notebook UI (using Jupyter backend).
We had used the following sample as a starting point https://github.com/microsoft/vscode-python.
Things are working as expected. We are currently using the following versions of the npm packages
```json
        "@jupyterlab/services": "^4.2.0",
        "@jupyter-widgets/schema": "^0.4.0",
        "@jupyter-widgets/base": "^2.0.1",
        "@jupyter-widgets/controls": "^1.5.2",
        "@jupyter-widgets/jupyterlab-manager": "^1.0.2",
        "@jupyter-widgets/output": "^2.0.1",
        "@jupyterlab/coreutils": "^3.1.0",
        "@phosphor/widgets": "^1.9.3",
```
As you can see, some of these are fairly old versions when compared to the latest versions on npm.
We have not encountered any situation where we have had to update any of these packages, i.e. users haven't reported any issues.

**Questions** 
* Should we update to the latest versions of these packages? 
* What are the implications of not updating?
* What are the implications of not updating?  
	Is it possible that IPyWidgets would stop working for some users. At the end of the day, updating the packages seems to make an assumption that the Jupyter server will have the same API compatibility (api & messages).

If there's any advice or recommendation on the above, we'd really appreciate it.
Once again, nothing related to IPyWidget support in our extension is broken.

Thanks
@jasongrout /cc

**Comment by vidartf** [comment]
These are my thoughts off the top of my head. I'm sure @jasongrout will correct me if I'm inaccurate, or miss something :)

Most jupyter lab extensions for ipywidgets only depend directly on `@jupyter-widgets/base` (for getting the manager token and the base types). With lab 3 coming out, there might be some changes to how extensions are *distributed*, but it shouldn't change whether they are installable/compatible. As the base package doesn't change much, it is mostly stable across major version releases of the ipywidgets Python package.

> Is it possible that IPyWidgets would stop working for some users

Do you control the Python dist as well, or are you using whatever the user already has? If the Python side version of the widget extension and the frontend version go out of sync (strictly: their synchronization spec does not match up, see spec for core widgets [here](https://github.com/jupyter-widgets/ipywidgets/tree/master/packages/schema)), then they will simply not display. If you do not control the Python dist yourself, the new federated extension distribution system for lab might be helpful to you (although the transition might be a little awkward?).

Another concern might be the planned 8.0 version of ipywidgets, which could prompt extension authors to drop support for older versions (mainly due to the phosphor -> lumino dependency rename). One of the main motivations for that version is a JS side refactor to allow third party extension authors to not need to update their extensions every time there is a new lab release.

**Comment by tonnydourado** [comment]
Not sure if related, but I've been trying to make ipywidgets work inside vscode for a while without success. Tried several combinations of setting up the virtualenvs and installing and enabling things, but I always get this error:

```
error 13:22:53.520: Widget load failure {} {
  className: 'TextStyleModel',
  moduleName: '@jupyter-widgets/controls',
  moduleVersion: '2.0.0',
  cdnsUsed: false,
  isOnline: true,
  timedout: false,
  error: '{}'
}
error 13:22:53.570: Widget Error: Error: Failed to render widget abb45c0ed9d142d986f74c68f079577f, Error: Module @jupyter-widgets/controls, semver range ^2.0.0 is not registered as a widget module
```

**Comment by DonJayamanne** [comment]
I'm going to close this as we now know what needs to be done. There were some offline conversations as well (in ipywidgets community meetings)
