### ISSUE TITLE
set_titles does not set titles of children in accordion or tab constructor

### ISSUE THREAD

**Issue by maxshowarth** [jupyter-widgets/ipywidgets#3180]
## Description

set_titles does not set titles of children in accordion or tab constructor in V 8.0.0a4. Titles are blank/not displayed. Accessing the instance's titles shows that they are set correctly.

I am aware that 8.0.0a4 is a pre-release, however, I believe this was working correctly in earlier builds and couldn't find the bug tracked anywhere. Please delete if I missed it.

## Reproduce

Run the following sample code from the documentation in a cell:
```
accordion = widgets.Accordion(children=[widgets.IntSlider(), widgets.Text()], titles=('Slider', 'Text'))
accordion #Titles are not displayed
accordion.titles #Titles tuple is displayed and shows the values were set correctly
```

## Expected behavior

Expected tabs and accordions to display titles "Slider" and "Text" as per documentation in the same fashion as .set_titles in 7.X

## Context

- ipywidgets version  8.0.0a4
- Operating System and version: Windows 10
- Browser and version: Chrome 89.0.4389.114

<details><summary>Troubleshoot Output</summary>
<pre>
Paste the output from running `jupyter troubleshoot` from the command line here.
You may want to sanitize the paths in the output.
</pre>
</details>

<details><summary>Command Line Output</summary>
<pre>
Paste the output from your command line running `jupyter lab` (or `jupyter notebook` if you use notebook) here, use `--debug` if possible.
</pre>
</details>

<details><summary>Browser Output</summary>
<pre>
Paste the output from your browser Javascript console here.
</pre>
</details>

### If using JupyterLab
- JupyterLab version:

<details><summary>Installed Labextensions</summary>
<pre>
Paste the output from your command line running `jupyter labextension list`.
</pre>
</details>

**Comment by jtpio** [comment]
Thanks @maxshowarth for the report and for testing the 8.0 alpha release!

Adding to the 8.0 milestone, in case this is a minor bug to fix and someone would like to take a look.

**Comment by ianhi** [comment]
Hi @maxshowarth are you in notebook or jupyterlab? I'm unable to replicate this on jlab3 with the latest ipywidgets alpha:

![image](https://user-images.githubusercontent.com/10111092/116936418-d0b99700-ac35-11eb-9b94-1eee047e03b9.png)

This also works for me on the latest binder: https://mybinder.org/v2/gh/jupyter-widgets/ipywidgets/master?urlpath=lab/tree/docs%2Fsource%2Fexamples

Can you try to replicate this in a fresh conda environment?

**Comment by felipecustodio** [comment]
I encountered the same issue running ipywidgets on Google Colab.
Should I open a different issue because of the different environment?

![image](https://user-images.githubusercontent.com/4261743/119024381-6153df00-b979-11eb-90ca-c250470ddde0.png)

![image](https://user-images.githubusercontent.com/4261743/119024350-59943a80-b979-11eb-97cb-9a5ec3f08782.png)

**Comment by jasongrout** [comment]
This also works for me in JLab 3 with the new 8.0a5 release:

![Screen Shot 2021-06-29 at 10 56 14 AM](https://user-images.githubusercontent.com/192614/123845194-c0860700-d8c8-11eb-821b-05e500d1a98b.png)

Since there has been no response, I'll close this. @maxshowarth, if you can reproduce this in a fresh environment, please let us know and we can reopen this.
