### ISSUE TITLE
hold_trait_notifications

### ISSUE THREAD

**Issue by fleming79** [jupyter-widgets/ipywidgets#3206]
Those familiar with Traitlets might be tempted to use `hold_trait_notifications` when updating widgets that have bounds.

For me, executing the following code in a JupyterLab cell causes Jupyter to crash (v2 and v3 on WinPython3940 & ipywidgets 7.6.3).  
```
import ipywidgets
sl = ipywidgets.IntSlider(min=0, max=1)
display(sl)
with sl.hold_trait_notifications():
    sl.min = 2
    sl.max = 3
```

The following code does not crash as the widget is updated before being displayed.
```
import ipywidgets
sl = ipywidgets.IntSlider(min=0, max=1)
#display(sl)
with sl.hold_trait_notifications():
    sl.min = 2
    sl.max = 3
display(sl)
```
It can be made to crash by using `hold_trait_notifications` as follows:
```
with sl.hold_trait_notifications():
    sl.min = 4
    sl.max = 5
```

Ideally, it would be best if it didn't crash. But if `hold_trait_notifications` is something that should not be used with ipywidgets then it may be worth mentioning in the documentation (I didn't find anything with the search box). This gotcha took me all day to track down.  Other than that I am very happy with the ipywidgets and am looking forward to the v8 release.

**Comment by jmandreoli** [comment]
Same problem here (same motivations).

Note that in @fleming79 's first example, if notifications were not held, `sl.min = 2` would result in an error (since min is greater than max). Then `sl.max = 3` restores a situation where there is no error. This seems to be the configuration which causes jupyter to crash when notifications are held.

Doing `sl.max = 3` before `sl.min = 2` produces no error and no crash.

Note that "jupyter crash" means the jupyter client page crashes. The server is unaffected.

**Comment by mwcraig** [comment]
Thanks  for providing a detailed bug report, @fleming79!

I no longer see this crash in ipywidgets 8.1/jupyterlab 3, so I'm going to close this issue. However, if you are still encountering it, please feel free to reopen it.

I think there is still a related bug happening when you try to set the value but I'll open a separate issue for that and refer to this one.
