### ISSUE TITLE
Audit styling attributes across widgets

### ISSUE THREAD

**Issue by jasongrout** [jupyter-widgets/ipywidgets#3257]
As brought up in discussion from https://github.com/jupyter-widgets/ipywidgets/pull/2728, it would be nice to unify some of the styling attributes various widgets have, and make sure they are used consistently across all widgets (a style `background` attribute was one thing brought up there, for example).

**Comment by vidartf** [comment]
Looking at the latest spec, and grepping for "StyleModel", this is their support for `background` field:
- [] ButtonStyleModel 
- [x] CheckboxStyleModel 
- [] DescriptionStyleModel 
- [x] HTMLMathStyleModel 
- [x] HTMLStyleModel 
- [x] LabelStyleModel 
- [] ProgressStyleModel 
- [] SliderStyleModel 
- [x] TextStyleModel 
- [] ToggleButtonStyleModel 
- [] ToggleButtonsStyleModel 

There are certain of these where it doesn't make sense to add the field for (e.g. button, as overriding it might make it seem unresponsive to click events), but it might be ok to add support for it, but document the potential pit fall for users?

This issue is also about potentially other fields, e.g. `font_weight` is just supported by 4 style models. so maybe the result of this audit should be a table of StyleModels x styling attributes.

**Comment by vidartf** [comment]
<table>
<tr>
<th>Attribute</th><th>ButtonStyleModel</th> <th>CheckboxStyleModel</th> <th>DescriptionStyleModel</th> <th>HTMLMathStyleModel</th> <th>HTMLStyleModel</th> <th>LabelStyleModel</th> <th>ProgressStyleModel</th> <th>SliderStyleModel</th> <th>TextStyleModel</th> <th>ToggleButtonStyleModel</th> <th>ToggleButtonsStyleModel</th> </tr><tr><td>background</td><td></td> <td>X</td> <td></td> <td>X</td> <td>X</td> <td>X</td> <td></td> <td></td> <td>X</td> <td></td> <td></td> </tr><tr><td>font_weight</td><td>X</td> <td></td> <td></td> <td></td> <td></td> <td>X</td> <td></td> <td></td> <td></td> <td>X</td> <td>X</td> </tr><tr><td>button_color</td><td>X</td> <td></td> <td></td> <td></td> <td></td> <td></td> <td></td> <td></td> <td></td> <td></td> <td></td> </tr><tr><td>text_decoration</td><td>X</td> <td></td> <td></td> <td></td> <td></td> <td>X</td> <td></td> <td></td> <td></td> <td>X</td> <td></td> </tr><tr><td>description_width</td><td></td> <td>X</td> <td>X</td> <td>X</td> <td>X</td> <td>X</td> <td>X</td> <td>X</td> <td>X</td> <td>X</td> <td>X</td> </tr><tr><td>handle_color</td><td></td> <td></td> <td></td> <td></td> <td></td> <td></td> <td></td> <td>X</td> <td></td> <td></td> <td></td> </tr><tr><td>text_color</td><td>X</td> <td></td> <td></td> <td>X</td> <td>X</td> <td>X</td> <td></td> <td></td> <td>X</td> <td>X</td> <td></td> </tr><tr><td>button_width</td><td></td> <td></td> <td></td> <td></td> <td></td> <td></td> <td></td> <td></td> <td></td> <td></td> <td>X</td> </tr><tr><td>font_family</td><td>X</td> <td></td> <td></td> <td></td> <td></td> <td>X</td> <td></td> <td></td> <td></td> <td>X</td> <td></td> </tr><tr><td>font_style</td><td>X</td> <td></td> <td></td> <td></td> <td></td> <td>X</td> <td></td> <td></td> <td></td> <td>X</td> <td></td> </tr><tr><td>bar_color</td><td></td> <td></td> <td></td> <td></td> <td></td> <td></td> <td>X</td> <td></td> <td></td> <td></td> <td></td> </tr><tr><td>font_variant</td><td>X</td> <td></td> <td></td> <td></td> <td></td> <td>X</td> <td></td> <td></td> <td></td> <td>X</td> <td></td> </tr><tr><td>font_size</td><td>X</td> <td></td> <td></td> <td>X</td> <td>X</td> <td>X</td> <td></td> <td></td> <td>X</td> <td>X</td> <td></td> </tr></table>

**Comment by jasongrout** [comment]
For 8.0, let's put this awesome table in the docs, and worry about filling it out more in 8.1?
