### ISSUE TITLE
Math / Latex rendering (with both HTMLMath and Label widgets) not working in Colab

### ISSUE THREAD

**Issue by adrien-perello** [jupyter-widgets/ipywidgets#3291]
## Summary

Math (latex) formula using the ipywidgets.**HTMLMath** and ipywidgets.**Label** only render in jupyter notebook and jupyter lab, **but not** in google colab ~~or vs code~~.

## Context

I build an interface that links some sliders with their mathematical representation (for example a Matrix where each value can be modified by a slider).
I use a grid widget to have in the same cell the mathematical representation on one side, and the sliders on the other

## Behavior

With **Jupyter Notebook** and **Jupyter lab** --> It works perfectly

![Screenshot from 2021-10-03 14-58-38](https://user-images.githubusercontent.com/76055749/135754785-9d265ec8-0635-4366-ba46-777e1a5cc5d9.png)

It does not work in **google colab**

![Screenshot from 2021-10-03 14-56-44](https://user-images.githubusercontent.com/76055749/135754787-9d421d80-4d5e-4e37-9ab2-12955385e971.png)

~~It does not work in **Vscode** either~~

![Screenshot from 2021-10-03 14-57-20](https://user-images.githubusercontent.com/76055749/135830070-228baec5-712e-4ed6-98b7-d167cd280802.png)

## Conclusion

What I don't understand is that if I use ```from IPython.display import Math```, then the Latex formula will render in both VScode and Colab. 
**But** if I do this, I can not use it inside my **Grid** (which *only accepts other widgets* as children). I have to display it in a different cell.

Maybe there is a workaround, but I have spent a few hours looking for it, and I didn't find it. What are other ways to go about it that I did not think of?

## [EDIT]
My bad, it actually works in VScode. 
![Screenshot from 2021-10-04 11-45-54](https://user-images.githubusercontent.com/76055749/135830073-df9d534b-c21e-4361-b0ed-97f9dd2bf316.png)
So maybe this is something specific to colab?

**Comment by claresinger** [comment]
I am having the same trouble on Colab. Formatting strings with `$...$` works fine with Jupyter lab, but doesn't render with colab. Any fixes?

**Comment by jasongrout** [comment]
For Colab issues like this one, please create an issue at https://github.com/googlecolab/colabtools.

**Comment by blois** [comment]
For reference, this is because Colab doesn't load MathJax into the sandboxed iframes by default, which then skips the typesetting here:
https://github.com/jupyter-widgets/ipywidgets/blob/bcbe52d58b5cc281328d7fb78aa4be924dce494f/packages/controls/src/utils.ts#L20

If a display item of type `text/latex` is displayed then we'll load KaTeX and render the string with that. While Colab uses MathJax for rendering in the main frame for compatibility reasons, it uses KaTeX in the outputs because MathJax loading is quite heavy and slow.

We'll probably need to overwrite the `DescriptionView.prototype.typeset` to customize, but the hard MathJax reference seems like it could be an issue elsewhere as well as clients look to move to MathJax v3 and/or KaTeX.

**Comment by jasongrout** [comment]
Thanks for your analysis, Pete. I still think the widget manager should be the one to provide a typeset function, which would then be easy to override.
