### ISSUE TITLE
Observe key bug

### ISSUE THREAD

**Issue by keivan-ardam** [jupyter-widgets/ipywidgets#3430]
## Description

![image](https://user-images.githubusercontent.com/59176054/162425053-9ddd2008-d4f5-4e8d-afc7-e51a43e7ff28.png)

Within this tog_handler, it is expected to see only "A" or "B" whenever either A or B is selected. 
But it seems to be executed 5 times when each button is observed (you would see 5 distinct rows). Same thing happens for the other widgets associated with observe function.

![image](https://user-images.githubusercontent.com/59176054/162427160-800cfb48-dfcf-45e9-8cb0-2a33f3e50115.png)

## Reproduce

2. Click on '...'
3. Scroll down to '...'
4. See error '...'

## Expected behavior

Only one line showing "A" or "B" whenever the corresponding button is selected.

## Context

- ipywidgets version: 7.7.0
- Operating System and version: VSCode (Python 3.9), Google Colab, Jupyter_hub
- Browser and version:

<details><summary>Troubleshoot Output</summary>
<pre>
Paste the output from running `jupyter troubleshoot` from the command line here.
You may want to sanitize the paths in the output.
</pre>
</details>

<details><summary>Command Line Output</summary>
<pre>
Paste the output from your command line running `jupyter lab` (or `jupyter notebook` if you use notebook) here, use `--debug` if possible.
</pre>
</details>

<details><summary>Browser Output</summary>
<pre>
Paste the output from your browser Javascript console here.
</pre>
</details>

### If using JupyterLab
- JupyterLab version:

<details><summary>Installed Labextensions</summary>
<pre>
Paste the output from your command line running `jupyter labextension list`.
</pre>
</details>

**Comment by jasongrout** [comment]
Thanks for posting here! The output widget accumulates output over time. The way to do what you want is to clear the output every time the function is triggered:

See the documentation for output widget at https://ipywidgets.readthedocs.io/en/stable/examples/Output%20Widget.html

```python
from IPython.display import clear_output

def tog_handler(obj):
    with out:
        clear_output()
        display(tog.value)
```

or perhaps simpler, declare the output widget first, and use the capture decorator

```
@out.capture(clear_output=True)
def tog_handler(obj):
    display(tog.value)
```

**Comment by kartfull** [comment]
Dear Jason, 

Thank you for your feedback. 

I skipped the clear_output by purpose in order to show the issue. 

The screenshot that I uploaded is the result of the cell when I just click "ONCE" on the enabled button. It should be one line but it seems that it switches between the buttons and as the result the handler would be executed 5 times while I just clicked once.

**Comment by jasongrout** [comment]
Ah, very true. You should also observe just the attribute you want to trigger a change for (i.e., 'value'), not all attributes of the widget that could change:

```python
tog.observe(tog_handler, 'value')
```

P.S. For next time, it's easier to reproduce your issue if you paste the actual code into the issue description as text, so others can just copy-paste your code, rather than having to retype your code from a screenshot. For others, here is the code:

```python
from ipywidgets import Output,VBox,ToggleButtons

def tog_handler(obj):
    with out:
        display(tog.value)

out=Output()
tog=ToggleButtons(options=['A','B'])
tog.observe(tog_handler)
VBox([tog,out])
```

**Comment by kartfull** [comment]
Thanks a lot, Jason, for your response.
Thanks for clarifying that, I understand now.
