### ISSUE TITLE
Dropdown menu ipywidgets show too many options

### ISSUE THREAD

**Issue by hhlim333** [jupyter-widgets/ipywidgets#3763]
Dropdown menu ipywidgets show too many options.

Can I set the number of options showing in the dropdown menu?

I am using ipywidgets 7.7.1.

Thank you 

The below is the picture from google colab 

![螢幕截圖 2023-04-24 15 17 37](https://user-images.githubusercontent.com/118234430/233925770-84323816-ff3b-4208-8221-691181c58ea3.png)

**Comment by jasongrout** [comment]
> Can I set the number of options showing in the dropdown menu?

No, it's just using the standard operating system dropdown control (it looks like macos in this case?), and the operating system makes those decisions.

You could use a Select widget to have a limited number of options shown, but then it wouldn't be a dropdown. You could also look into using ipyvuetify or ipymaterialui to have a richer set of controls - since they have written their own dropdowns, they might give you that control.
