### ISSUE TITLE
option to display Tab and Accordion on hover?

### ISSUE THREAD

**Issue by hainm** [jupyter-widgets/ipywidgets#696]
Something likes this: http://arose.github.io/ngl/ (File-View-...). What do you think?

**Comment by gnestor** [comment]
@hainm Not exactly sure what you mean here...

**Comment by hainm** [comment]
@gnestor  currently we need to 'click' the Tab, what's about 'hover' the tab.

**Comment by gnestor** [comment]
It seems to me that it's more conventional to click a tab to *open* it vs. hover over it. Is there a good reason to stray from convention given Jupyter/ipywidget's diverse user base?

**Comment by hainm** [comment]
I think it is just personal taste. 

PS: I am not talking about 'replacing click' but adding one more option.

tab = Tab([...], hover=True)

Hai

**Comment by gnestor** [comment]
Ok, I gotcha. I invite you to submit a PR with an example implementation 👍

**Comment by jasongrout** [comment]
I think we should stick with the prevailing conventions when it comes to tabs and accordions, i.e., click changes state. It looks like the example above is for *menus*, which we don't have in the base controls. If menus are desired, I suggest writing a menu control as a custom widget.

Closing since there has been no action.

**Comment by jasongrout** [comment]
(and the ngl web app above looks really cool!)
